# /etc/rsyslog.d/10-octosip-honeypot.conf
# Receives logs from Kamailio (LOCAL0) and passes them to the parser.

module(load="omprog")

if $syslogfacility-text == 'local0' then {
    action(
        type="omprog"
        binary="/opt/octosip/venv/bin/python3 OCTOSIP_DIR_PLACEHOLDER/octosip_parser.py"
        confirmMessages="off"
        queue.type="LinkedList"
        queue.size="50000"
    )
    stop
}
