# /etc/rsyslog.d/10-sip-honeypot.conf
# Receives logs from Kamailio (LOCAL0) and passes them to the parser.

module(load="omprog")

if $syslogfacility-text == 'local0' then {
    action(
        type="omprog"
        binary="/opt/sipmon/bin/python3 /opt/sipmon/sipmon_parser.py"
        confirmMessages="off"
        queue.type="LinkedList"
        queue.size="50000"
    )
    stop
}
